server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mail:
    host: smtp.qq.com
    port: 587
    username: @qq.com
    password: 授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: your-jwt-secret-key
  expiration: 86400000 # 24小时

logging:
  level:
    root: INFO
    com.blog: DEBUG